# Generated by Django 3.1.4 on 2021-05-11 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=120)),
                ('Picture', models.FileField(default='defaultComponent.png', null=True, upload_to='')),
                ('description', models.TextField(max_length=120)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('note', models.CharField(default='', max_length=120, null=True)),
                ('purchased_at', models.DateField(auto_now_add=True)),
                ('Quantity_in_stock', models.IntegerField(default=1)),
                ('Quantity', models.IntegerField(default=1)),
                ('Category', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateField(auto_now_add=True)),
                ('Reason', models.TextField()),
                ('Quantity', models.IntegerField(default=1)),
                ('return_at', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('material', models.ManyToManyField(to='materials.Material')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
